from __future__ import annotations

from datetime import datetime
from typing import Protocol

from agentic_sim.models import (
    AgentId,
    AgentProfile,
    AgentState,
    EnvironmentState,
    Event,
    Message,
    TraceRecord,
)


class AgentStore(Protocol):
    def get_profile(self, agent_id: AgentId) -> AgentProfile: ...
    def put_profile(self, profile: AgentProfile) -> None: ...
    def list_profiles(self) -> list[AgentProfile]: ...
    def get_state(self, agent_id: AgentId) -> AgentState: ...
    def put_state(self, state: AgentState) -> None: ...


class EventStore(Protocol):
    def put(self, event: Event) -> None: ...
    def put_many(self, events: list[Event]) -> None: ...
    def pop_ready(self, now: datetime, limit: int | None = None) -> list[Event]: ...
    def count_pending(self) -> int: ...


class MessageStore(Protocol):
    def put(self, message: Message) -> None: ...
    def put_many(self, messages: list[Message]) -> None: ...
    def inbox(self, agent_id: AgentId, limit: int = 10, after: str | None = None) -> list[Message]: ...
    def count(self) -> int: ...


class EnvironmentStore(Protocol):
    def get(self) -> EnvironmentState: ...
    def put(self, state: EnvironmentState) -> None: ...


class TraceStore(Protocol):
    def put(self, trace: TraceRecord) -> None: ...
    def list(self) -> list[TraceRecord]: ...


class RuntimeStore(Protocol):
    agents: AgentStore
    events: EventStore
    messages: MessageStore
    environment: EnvironmentStore
    traces: TraceStore
